version: '3.6'
services:
  elasticsearch:
    build: .
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      -
        type: volume
        source: nakedesdata
        target: /usr/share/elasticsearch/data
      -
        type: bind
        source: /Users/dcorking/facabackup
        target: /backups
    ports:
      - 9200:9200
volumes:
  data:
  nakedesdata:
    driver: local
